### ISSUE TITLE
Planets not Visible in Selector

### ISSUE THREAD

**Issue by GroupXyz1** [TathanDev/StarWarsPlanets-AdAstra#1]
I played it with friends on a Forge Server 1.19.2, and as we flought up with the rocket, in the Planet selection Menü was Milkway, but not any othe Galaxis and also not in the Submenü Like Alpha Centauri or so on. The Planets just don't appear in the Selector, can u fix that?

**Comment by TathanDev** [comment]
Yea sure, I'll check that

**Comment by GroupXyz1** [comment]
Ok here is some Extra Information, because i guess i forgot some: It is from Curseforge, this Version: SWPlanets-forge-1.19.2-1.0.6.3.jar On the Server this is Installed too, and also Ad Astra, but no Library Mods for SW-Planets, because it seems to need none (exept Ad Astra but thats no lib), i hope thats not the failure but i guess not. And It WORKS ON SINGLEPLAYER, with the same Modpack, but NOT ON THE MULTIPLAYER SERVER. So the only thing i noticed on The Server that it actually loaded and not just didn't load was the purple Head Category Milky Way in the Planet Selection Menu, but also the Items were not in JEI visible, because i searced for "Laser" and "Lasersword" and "@SWPlanets" and "@StarWarsPlanets" but no results. I hope this makes it a bit easier for u to find the Error :D

**Comment by TathanDev** [comment]
Which version of Ad Astra are you using ?
Because it work for me
![image](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/67022946/c7d88ee4-2a43-4f89-adec-0a478a0f16f0)

**Comment by TathanDev** [comment]
Which version of Ad Astra are you using ?
Because it's work for me
![image](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/67022946/059e686e-4c63-4b3d-aefb-ef316d830998)

**Comment by GroupXyz1** [comment]
Yeah in Singleplayer it works, it looks exactly like Yours, but on our Multiplayer Server it does not Show the "The Galaxy" Menu, so it has something to to with the Server wait i make one Screenshoot in singleplayer and one with the Same Modpack on Multiplayer. btw also i Noticed this Orbit Noice from Ad Astra while beeing on the Planet in singleplayer, and i have to say it was a bit getting on my nerves maybe that could be deactivated on Planets with an Atmosphere. But anyways here the Screenshoots: 
Singleplaer:
![Screenshot (274)](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/122233274/7b720fa6-7447-4b5f-9a0a-8231e55e023d) 

![Screenshot (275)](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/122233274/84927ae7-dc26-42a5-be0f-71fe3dd5cf97)
maybe you need a list of the Server Side Installed Mods, ill send a list of them as soon as the Owner is on

**Comment by GroupXyz1** [comment]
Whooa the Screens were both from Multiplayer sorry wait this is singleplaer:
![Screenshot (272)](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/122233274/3d9649bd-ccff-4da0-80c9-66f91e4c5f1d)

**Comment by TathanDev** [comment]
Can i see your modpack ?
Because my screenshot was take in multiplayer

**Comment by GroupXyz1** [comment]
Yo here is the Server Folder from Multiplayer:
[https://mega.nz/folder/0TFwiIpD#0PuwPCVmX9WEP6mFwkjGhQ](url)
And here is the Client Side Mod folder:
https://1drv.ms/u/s!AnW6-HqwRRePgn9gD7svFjb-q-YL?e=iibpnX

**Comment by TathanDev** [comment]
Ok i found the problem : you use the fabric version of SWPlanets
![image](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/67022946/1bd56e98-39cd-4ce1-be69-e74d6ccb939d)
Here the Forge version : https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/files/4520256

**Comment by GroupXyz1** [comment]
Thanks, i really did not expect this, but wow the server owner is so smart lul.
Really Thanks 4 ur help, i am really hyped to explore the Planets with my Friends.
