### ISSUE TITLE
Not sure if this is an issue

### ISSUE THREAD

**Issue by ModernGamingWorld** [TathanDev/StarWarsPlanets-AdAstra#11]
Currently Your Latest version for SWPlanets-fabric-1.20.1-ALPHA-1.2.1 is showing up as a update for the Forge version of the mod for 1.20,1. idk if this was intended
![Screenshot 2023-12-31 173934](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/75923060/f03e4c7d-8890-4c05-94aa-8a0c25be5747)

**Comment by TathanDev** [comment]
Thanks for the report, I uploaded the wrong version

You can download the new version here : https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/files/4999003

Thanks!
