### ISSUE TITLE
Fabric Jar Marked as Forge on Curseforge

### ISSUE THREAD

**Issue by ModernGamingWorld** [TathanDev/StarWarsPlanets-AdAstra#14]
Hi, I posted about this a few days ago, and it looks like you did it again with the latest update by including SWPlanets-fabric-1.20.-1.2.2.jar as a forge version. Whenever you posted the update, you posted both Forge and Fabric under the Forge Modloader on Curseforge. I don't know if this is a tag issue or not. This could always be a bigger problem if Modpack developers don't know to check that you are somehow mislabeling modloaders.

**Comment by TathanDev** [comment]
Thanks for this report !
I really need to add auto publishing to curseforge X)

I changed it on curseforge and it should appear like a fabric mod !
