### ISSUE TITLE
Sandstone Kyber Crystal Ore does not drop Kyber Crystals.

### ISSUE THREAD

**Issue by NavonodAU** [TathanDev/StarWarsPlanets-AdAstra#2]
I mined Sandstone Kyber Crystal Ore with netherite pickaxes but the block will not drop the Kyber Crystals.
I had to go to Endor and mine Kyber Crystal Ore to get Kyber Crystals.

Also when trying to mine Sandstone Kyber Crystal Ore it takes about as long as obsidian to mine it.

**Comment by TathanDev** [comment]
Thanks for reporting this issue !
Which Minecraft version are you using?

**Comment by NavonodAU** [comment]
1.19.2 using the latest forge currently and your most recent update of the mod.

**Comment by TathanDev** [comment]
Ok !
The bug is fixed.
You can download the new release here : [https://legacy.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/files/4550864](https://legacy.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/files/4550864)
