### ISSUE TITLE
1.19.4 version did not recognize 1.19.4

### ISSUE THREAD

**Issue by Cape-City** [TathanDev/StarWarsPlanets-AdAstra#3]
Hi,

your new release on CurseForge for 1.19.4 the fabric.mod.json isn't correct:

![grafik](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/122229367/e86efe0d-9bd8-4a94-9acd-398552768986)

and then this version is not running on 1.19.4

![grafik](https://github.com/TathanDev/StarWarsPlanets-AdAstra/assets/122229367/9c6b0aeb-2d8b-45b0-a3d8-32f28b02342c)

**Comment by TathanDev** [comment]
Thanks for the report i'll fix that today !

**Comment by TathanDev** [comment]
This version sould fix this problem ; https://legacy.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/files/4566841

**Comment by Cape-City** [comment]
Thnx, issue is gone ;)
