### ISSUE TITLE
Some issues, comments and questions

### ISSUE THREAD

**Issue by drakray** [TathanDev/StarWarsPlanets-AdAstra#6]
Hello There!, nice mod you got :D
Some bugs(?):
-Beskar(item) is named Baskar
-Kylo's Saber uses green dye instead of red
-Dark Saber uses stick instead of saber base
-Dark Saber is not listed in JEI
-Mustafar can generate lava through bedrock
-Hoth is named Hot in PlanetGUI and dimension folder
-The Galaxy(planetgui) doesn't have an image(unlike Milky Way)
-Mandalore's Orbit doesn't have 0>256 y-level like other orbits, but -64>384, like the planets
-Hoth, Mustafar and Tatooine can't be slept on(I was surprised on Mandalore lol), Endor is sleepable
-AT-ST can spawn on water
-Tatooine's House can spawn partially floating

Some comments/questions:
-Darth Maul's Saber should have different stats since it cost 2 nether star to make, or maybe a different recipe
-Most planet are really barren, is there plans to make some ores spawn, or structures?
-Mandalore doesn't have beskar ore, is this intended?
-Beskar ore isn't affected by Fortune, and can't be picked by Silk Touch, is this intended?
-Tatooine's biome allow desert village, is this normal?(might be a conflict with another of my mods)
-The AT are very nice, but coul be even nicer with some loot ;)
-Also mobs(Trooper(neutral, zombiepiglin-style?), Ewok, Jawa(bartering?))

Thank you for your good work :)

**Comment by TathanDev** [comment]
Thansk for the bugs report !
Can i have your version and if you use fabric or forge ?

Thanks !

**Comment by drakray** [comment]
Yes sorry! lol
Minecraft 1.20.1
NeoForge 47.1.76
AdAstra 1.15.3
AdAstra Giselle 5.6
SW Planet 1.0.15
BunchaOtherMods™

**Comment by TathanDev** [comment]
Ok so i fixed :

- Beskar name
- Kylo's Saber 
- Dark Saber 
- Dark Saber (JEI)
- Hoth
- Mandalore's Orbit 
- Bed problem

For the Image in the GUI, i don't have a good image of the star wars galaxy that i can used and also the base image of ad astra don't work...

About the questions :
- I plan to add more structures, it's just that i'm not good for making small structures. I can also make bigger structures likes stronghold or end city but i need to learn how jigsaw blocks work
- For the mob, i'm so bad at modeling (but, like really !) so or the moment, it's not an option
- For the AT, yes, i will add loots (I though they were already loots x) )
- For the deserts villages, it's to add some life to the planets until i add more structures.
- Yes, i will add differents stats to the Darth Maul's light saber.
- The ore should gen, it's just rare (i will change thats)

I hope I've answered all your questions.

Thanks for the bugs reports and the suggestions !

**Comment by drakray** [comment]
I'll see if I can help you with some structure maybe ;)
For mobs, I think a simple reskined zombie with trooper armor would go a long way, maybe later(I should really get back on modding myself, GeckoLib seems to have many useful feature for mob management)

As for the Beskar Ore, I used ChunkPregen to generate a large Mandalore and Minutor to look at everything, and it is completely barren, only sand and smooth sandstone, weird :/
